### ISSUE TITLE
Exception On Android when calling scan, Missing Frameworks on iOS

### ISSUE THREAD

**Issue by Bobisback** [BlinkID/blinkid-xamarin#1]
Hello,

So I am trying to implement this project into an existing Xamarin forms application. 

For android if I call the "Scan" method just like the sample I get the following exception during runtime. 

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.microblink.wrapper.xamarin.scan.BlinkIDScanActivity}: 

[MicroBlinkIDError.txt](https://github.com/BlinkID/blinkid-xamarin/files/303458/MicroBlinkIDError.txt)

Attached is the full log.

If I add it to the iOS side of the project I get errors simular to this. This is compile errors, so I cannot even get the project to run.

error : Native linking failed, undefined symbol: non-virtual thunk to std::__1::basic_iostream<char, std::__1::char_traits<char> >::~basic_iostream(). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.

[MicroBlinkIDiOSLog.txt](https://github.com/BlinkID/blinkid-xamarin/files/303462/MicroBlinkIDiOSLog.txt)

Full log is attached

Any ideas what the issues could be?

Thanks,
Sean

**Comment by DoDoENT** [comment]
Hi,

do the demo apps work for you? Both android and ios crash indicate that some files are missing inside final app. This usually happens when improper integration is performed. Make sure you follow the [samples](https://github.com/BlinkID/blinkid-xamarin/tree/master/Samples) to the letter.

**Comment by Bobisback** [comment]
So that is the thing, the sample apps do work. So my thought is you are doing some setup in the demo apps that needs to be preformed for my app. Here is the issue you say follow the sample apps to the letter? What does this mean to "follow the samples to the letter", I have seen no instructions on how to install this into an existing app anywhere so what am I following to the letter????

Basically all I am doing atm is referencing the bindings dll in my new app. And obviously this is not working. If there is other steps that need to be preformed please let me know and more importantly get this documented somewhere.

**Comment by stepanic** [comment]
@Bobisback detailed documentation about how to install BlinkID into an existing application will be available soon.

At the screenshot are marked all key things in `Droid` project which is the platform specific project.

**Missing the first step produces errors to you**

1. You need to add existing assets from the Sample application:
`Assets/microblink/device_list.json`
and
`Assets/microblink/ocr_model.zzip`
The both of them should have `Build Action` -> `AndroidAsset`

2. To your Xamarin Forms application solution add existing project `BlinkIDAndroidBinding` and add reference to platform specific `Droid` project (this is marked with yellow at the screenshot)

3. Add `Camera` permission in the `Properties/AndroidManifest.xml`

4. Add existing file from the sample application of `BlinkIDImplementation.cs` and change License key for your Package name

![droid-platform-specific-project](https://cloud.githubusercontent.com/assets/315282/15903472/3d2dcd14-2dad-11e6-8550-b5019831399f.png)

**Comment by stepanic** [comment]
For iOS we need to fix Objective-C wrapper, I will notify when it will be done.

**Comment by Bobisback** [comment]
Thanks for the reply I will give this a shot shortly.

**Comment by Bobisback** [comment]
So I can get the camera and overlay to come up now, which is awesome. I am having a issue now where I cannot get it to scan the license. I am guessing I should be pointing this at the back of the license? Or does this scan the front as well? The image on this website would suggest you scan the front of the card: https://microblink.com/blinkid

I am just not sure as I sit there any hold it on hte back of the license and no luck on it scanning. I change the positions, and lighting with no luck. I have tried it on white backgrounds, dark backgrounds, grey backgrounds and nothing seems to change.

**Comment by stepanic** [comment]
Sample application has only two recognizers Mrtd - Machine-readable travel documents and Ukdl - United Kingdom driver license  
```
// Define recognizers
recognizers = new List<BlinkID.RecognizerType>();
recognizers.Add(BlinkID.RecognizerType.Mrtd);
recognizers.Add(BlinkID.RecognizerType.Ukdl);
```

If you want to support US Driver licences, add this line of code:
```
recognizers.Add(BlinkID.RecognizerType.Usdl);
```
![screen shot 2016-06-09 at 13 26 30](https://cloud.githubusercontent.com/assets/315282/15928195/d2d391da-2e45-11e6-896e-e4a851c6f51f.png)


Note: many numbers of recognizer will maybe cause slow results getting

At some licences, MRTD is at the front side of the card, like at our website.
https://en.wikipedia.org/wiki/Machine-readable_passport

**Comment by Bobisback** [comment]
Awesome thanks, I realized this after playing with it for a bit.

Thanks for the heads up. I got it working now.

Thanks!

**Comment by stepanic** [comment]
@Bobisback we fixed Binding library for iOS and new changes are available at `master` and we also updated README how to Quick start from an Existing app

Feel free to ask more questions in the future and we will respond to it as quick as possible
