### ISSUE TITLE
Android: Back side of the ID sometimes recognized as the front side

### ISSUE THREAD

**Issue by dinodzakmic** [BlinkID/blinkid-xamarin#11]
Hello,

I've used your sample project as a guide, set up all for Xamarin.Forms and I have this issue on Android.
Sometimes, SerbianID back is recognized as a front side. I've noticed this happens mostly when I scan ID in portrait mode (happened few times also in landscape mode, but rarely).

I used same principle as in your sample project, with BlinkID implementation in Droid project, with Messages class and all the necessary fields.
When scan is completed, I provide the results via the MessagingCenter.

 Please let me know if you need more details, some logs or stacktrace in order to fix this, or maybe I could fix this locally.

Thanks in advance,
Dino.

**Comment by i1E** [comment]
Hi @dinodzakmic,

can you please send us scans of the problematic documents to support@microblink.com? We will check what we can do to improve the scanning.

**Comment by dinodzakmic** [comment]
Thanks for answer, I've sent you an email.
