### ISSUE TITLE
Xamarin forms sample is not building

### ISSUE THREAD

**Issue by georgethms10** [BlinkID/blinkid-xamarin#13]
I downloaded the sample from the github but its not building its giving build errors. Please tell me how to remove the build error
<img width="1052" alt="screen shot 2018-07-10 at 12 09 59 pm" src="https://user-images.githubusercontent.com/6296111/42493367-6a1f0c6c-843a-11e8-9cd2-59057c7cfbcc.png">

**Comment by kfrancis** [comment]
@georgethms10 Did you figure this out or just give up?

**Comment by gsalve** [comment]
Getting the same issue, Android sample working but iOS project not running. Any help will be appreciable.

**Comment by gsalve** [comment]
Getting the same issue, Android sample working but iOS project not running. Any help will be appreciable.

<img width="1341" alt="screenshot 2018-11-29 at 3 52 14 pm" src="https://user-images.githubusercontent.com/5080586/49216776-e5086280-f3f1-11e8-9ac0-c5d5ab540ce1.png">

**Comment by HarlowBurgess** [comment]
Getting same issue as gsalve. Multiple "Native linking failed, undefined symbol" build errors for iOS project.

**Comment by jcular** [comment]
Hi @HarlowBurgess 

see [here](https://github.com/BlinkID/blinkid-xamarin/issues/22#issuecomment-443157604). You're probably running the app on simulator.

Kind regards,
Jure
