### ISSUE TITLE
The sample does not recognize any card

### ISSUE THREAD

**Issue by Pethical** [BlinkID/blinkid-xamarin#27]
The sample not working (Xamarin forms and Xamarin Android). I can't recognize any card. The sample from [Google Play](https://play.google.com/store/apps/details?id=com.microblink.blinkidapp) recognizing all.
### Steps to reproduce
1. Clone repository
2. Open in Visual Studio 2017
3. Build
4. Run on Android device
5. Try to recognize any card
### My configuration
- Visual studio 2017
- Xamarin Forms 3.4
- Huawei P Smart (Android 8.0)
### Tested cards
| Card | Worked with sample | Worked with the Google Play app |
| -------------------- | :----: | :----: |
| Hungarian ID Card |  ❌| ✔️ |
| Hungarian Driver License | ❌| ✔️ |
| New York Driver License | ❌| ✔️ |
| Arizona Driver License | ❌| ✔️ |
| Italy Driver License | ❌| ✔️ |
| UK Driver License | ❌| ✔️ |

The BlinkID Xamarin SDK is propably unusable.

**Comment by culoi** [comment]
Hello @Pethical 

Are you experiencing a crash or scanning just hang on scanning screen? 

Can you please share which recognizers are you setting in the project? Are you using default ones or you are adding some additional? 

Also, an important question. Are you scanning real documents or samples from the internet? 

Best regards

**Comment by Pethical** [comment]
Hi @culoi,

Nope. No hangup, no crash, the app is responsive, but nothing recognized.
I tried real documents, and sample documents from the internet, no one recognized, but your app from the play store recognizes all, so I think the documents are ok, but the Xamarin SDK has problems with there.

Thanks

**Comment by culoi** [comment]
Hello @Pethical 

If you are building the sample from the SDK, you have included MRTD, EUDL and USDL recognizer in the project. 

With MRTD and USDL we are scanning the MRZ line and PDF417 barcode from the back side of the document. 

Best regards

**Comment by Pethical** [comment]
Hi @culoi,

I used the unmodified source from this repo.
Did you include it?

https://github.com/BlinkID/blinkid-xamarin/blob/68e1dd0f7b206a01588a15a5ad63430b57e0d886/Samples/Forms/Core/BlinkIDPage.xaml.cs#L175

https://github.com/BlinkID/blinkid-xamarin/blob/68e1dd0f7b206a01588a15a5ad63430b57e0d886/Samples/Forms/Core/BlinkIDPage.xaml.cs#L183

https://github.com/BlinkID/blinkid-xamarin/blob/68e1dd0f7b206a01588a15a5ad63430b57e0d886/Samples/Forms/Core/BlinkIDPage.xaml.cs#L190

Yes. 😉 

**Please, read what I wrote.** I cloned this repo and I didn't modify the source code.

Regards,
 Peter

**Comment by culoi** [comment]
Hello @Pethical 

> **Please,read what I wrote.** I cloned this repo and I didn't modify the source code.

Now I have the correct information.

Our BlinkID Demo uses documentVerificationOverlay in which the user is prompted to scan first front and then the back side of the document.

In Xamarin we are using documentOverlay in which user scan only one side of the document. As on the mentioned documents mrtd and barcode is located on the back side. 

Can you please try to scan the back side of the Hungary ID and USDL (New York and Arizona) and see if you are able to get results? 

Regarding the Hungarian DL, we don't have support for that document. In our demo app, we only return the image of the document. 

For Italy DL, we added support in the version 4.3 of our SDK.

Best regards
