### ISSUE TITLE
Requires old version of Xamarin.Forms

### ISSUE THREAD

**Issue by markti** [BlinkID/blinkid-xamarin#28]
When trying to add reference to BlinkID.Forms

Restoring packages for 
NU1605: Detected package downgrade: Xamarin.Forms from 3.4.0.1008975 to 3.2.0.871581. Reference the package directly from the project to select a different version. 
 MyProj -> BlinkID.Forms 4.6.0 -> BlinkID.Forms.Core 4.6.0 -> Xamarin.Forms (>= 3.4.0.1008975) 
 MyProj -> Xamarin.Forms (>= 3.2.0.871581)
Package restore failed. Rolling back package changes for 'MyProj'.

when trying to add nuget reference to BlinkID.Forms.Core:

NU1605: Detected package downgrade: Xamarin.Forms from 3.4.0.1008975 to 3.2.0.871581. Reference the package directly from the project to select a different version. 
 MyProj -> BlinkID.Forms.Core 4.6.0 -> Xamarin.Forms (>= 3.4.0.1008975) 
 MyProj -> Xamarin.Forms (>= 3.2.0.871581)
Package restore failed. Rolling back package changes for 'MyProj'.

**Comment by jcular** [comment]
Hi @markti,

BlinkID requires version 3.4.0 or higher of Xamarin.Forms. You need to update your Xamarin.Forms package since its version is 3.2.0.

Kind regards,
Jure
