### ISSUE TITLE
Getting Invalid license key from sample project

### ISSUE THREAD

**Issue by blakenorman37** [BlinkID/blinkid-xamarin#33]
I am getting the following error when I am setting up Microblink following the Xamarin/Core example:
Java.Lang.RuntimeException: This license is invalid for licensee 'com.companyname'. It is valid only for licensee 'com.microblink.xamarin.blinkid', for product 'BlinkID' on platform 'Android' up to version 4.9. Please contact support for more information.

How do I run targeting Android 8.0?

**Comment by culoi** [comment]
Hi @blakenorman37,

Please make sure that you set proper licensee and license key. This error shows that you are using licensee com.companyname and you are using the license key that is generated for the com.microblink.xamarin.blinkid.

You can generate license key for your licensee on our dashboard: www.microblink.com/login

Regards

**Comment by blakenorman37** [comment]
@culoi , that worked. Thanks
