### ISSUE TITLE
Missing Asset in Android Sample

### ISSUE THREAD

**Issue by olibd** [BlinkID/blinkid-xamarin#4]
There's a missing asset in the android demo that's causing an exception.

The "face_detector_model.zzip" asset should be found under "blinkid-xamarin/Samples/Android/Assets/microblink"

**Comment by stepanic** [comment]
@olibd  This is fixed with 3d5406977777d443ead5b4f9368093bd0c9193c1

Use latest changes from `master` and Sample app should work.

Every Android app which use BlinkID should have assets from:
https://github.com/BlinkID/blinkid-android/blob/master/LibRecognizer.aar
