### ISSUE TITLE
Pixel 3 application crash on scan

### ISSUE THREAD

**Issue by jamesingreersc** [BlinkID/blinkid-xamarin#49]
This is a Xamarin Forms project using BlinkIDCustomForms package 5.3.0. 
QA just ran into a problem on a pixel 3 crashing when trying to scan. It works fine on my LG50 but I did just confirm on another pixel 3 that it does crash.  
Seems to be looking for a missing json file??
Below is the stack trace.

`` 06-26 15:55:06.028 E/AndroidRuntime(17723): FATAL EXCEPTION: main
06-26 15:55:06.028 E/AndroidRuntime(17723): Process: com.ger.hcmobile, PID: 17723
06-26 15:55:06.028 E/AndroidRuntime(17723): java.lang.RuntimeException: Cannot load asset microblink/device_list.json. Please make sure that this asset exists!
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at com.microblink.hardware.IlIllIlIIl.IllIIIllII(line:107)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at com.microblink.hardware.IlIllIlIIl.<init>(line:68)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at com.microblink.hardware.IlIllIlIIl.llIIlIlIIl(line:59)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at com.microblink.view.BaseCameraView.IllIIIllII(line:228)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at com.microblink.view.BaseCameraView.<init>(line:215)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at com.microblink.view.CameraViewGroup.<init>(line:67)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at com.microblink.view.recognition.RecognizerRunnerView.<init>(line:126)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at com.microblink.view.recognition.RecognizerRunnerView.<init>(line:133)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at com.microblink.fragment.RecognizerRunnerFragment.IlIllIlIIl(line:270)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at com.microblink.fragment.RecognizerRunnerFragment.onCreateView(line:223)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1432)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at android.app.Activity.performStart(Activity.java:7848)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at android.os.Handler.dispatchMessage(Handler.java:107)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at android.os.Looper.loop(Looper.java:214)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at java.lang.reflect.Method.invoke(Native Method)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
06-26 15:55:06.028 E/AndroidRuntime(17723): Caused by: java.io.FileNotFoundException: microblink/device_list.json
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at android.content.res.AssetManager.open(AssetManager.java:824)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at android.content.res.AssetManager.open(AssetManager.java:801)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	at com.microblink.hardware.IlIllIlIIl.IllIIIllII(line:97)
06-26 15:55:06.028 E/AndroidRuntime(17723): 	... 37 more
**Java.Lang.RuntimeException:** 'Cannot load asset microblink/device_list.json. Please make sure that this asset exists!'

**Comment by matvidako** [comment]
Hi,

we've had the same issue reported before, and it turned out that the fix is to simply rebuild the project.
Can you try doing that?

**Comment by jamesingreersc** [comment]
Hey. That worked. I had to close the project and delete all the bin/obj folders and then rebuild but now it is working. Not sure why the QA build was broken since it goes thru the Azure pipeline to hit Beta in the store which should have started with clean folders. If it keeps happening I will get a ticket opened but as of now it is working fine on my local machine.
