### ISSUE TITLE
Native linking error when trying to use the bound iOS lib from Xamarin.iOS

### ISSUE THREAD

**Issue by irreal** [BlinkID/blinkid-xamarin#5]
I'm having trouble using the library from any Xamarin.iOS project. The BlinkIDiOSBinding project builds without any errors, but building the actual iOS project that references the bound lib breaks with "Native linking error: framework not found MicroBlink (MT5209)"
This is the same for both the iOS sample and the Xamarin.Forms sample from the repo.
I even tried removing the binding project and referecing the built .dll from the Xamarin.iOS project, but it still won't compile.
The android version works without any problems.

**Comment by irreal** [comment]
I was able to compile the app that is referencing the BlinkIDiOSBinding project in visual studio, by adding the [Protocol] attribute on the BlinkID interface in ApiDefinition.cs
so
```
[BaseType (typeof(NSObject))]
    [Protocol]
	interface BlinkID
	{
```
but now the sample just crashes on
`BlinkID.Instance().LicenseKey = "VVBZXXL4-YIHNFMHI-V3RF6KDA-WPFHFFEX-5X72P6VO-55RZ66YJ-IYVFVAOY-MYETCD5W";`

as the .Instance() call returns null.

So I'm still stuck. I am unable to compile your sample projects from either Visual Studio on windows or Xamarin Studio on OS X, running latest stable xamarin.

**Comment by Cerovec** [comment]
This error is related to the fact that there is no framework (binary) found in the repository.

The repository contains a git submodule to the BlinkID SDK (native).
BlinkID SDK has binary stored on git lfs (large file storage).

So we would recommend the following

1) install git lfs

```bash
brew install git-lfs
git lfs install
``` 

Note: if you don't have Homebrew installed, follow the instructions from here: http://brew.sh

2) clone the repository and use the cloned repo instead of just regular download. Clone is important because the repository contains submodules.

```bash
git clone git@github.com:BlinkID/blinkid-xamarin.git
``` 

3) Fetch all submodules

```bash
git submodule init
git submodule update --recursive
``` 

4) After that, try the BlinkIDiOSBinding project and let us know if it works :)

**Comment by irreal** [comment]
Thanks, that indeed solved it. Compiles with no issues now.

**Comment by ducas** [comment]
Can the git LFS requirement _please_ be added to the README...? I was banging my head against the desk for 3hrs trying to figure this out. 😿

**Comment by marualderete** [comment]
Hi! I'm trying to implement BlinkSDK in my PCL xamarin projects, and I same issue
I do the steps Cerovec put in a previous comment
From a terminal, I go in to my project folder, then I did those steps

After that, I go to XS IDE and Add BlinkIDiOSBinding project to my solution. And this builds ok. But when I add  the BlinkIDiOSBinding reference in to MyApp.iOS Project, both errors appears.

Can you help me please? What am I missing? I put [Protocol] in BlinkID interface too, but nothing.

**Comment by DrTJ** [comment]
@Cerovec Your solution worked for me! Thank you.

**Comment by msmrajesh** [comment]
Hi

When trying to fetch all submodules I am getting this error

$ git submodule update --recursive
Cloning into 'C:/Users/a/blinkid-xamarin/BindingSource/iOS/blinkid-ios'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I am able to clone the repository but unable to download all the submodules.

How can I get all the binaries for this framework for iOS.

Thanks,

Rajesh.

**Comment by RushikPatel** [comment]
Hello Guys,

Getting issue when build existing project.

       Severity	Code	Description	Project	File	Line	Suppression State
       Error		Native linking failed. Please review the build log.	test.iOS			
       Error		Native linking error: library not found for -lVidyoClient	test.iOS			
       Error		Native linking failed. Please review the build log and the user flags provided to gcc: "- 
      LNative References" -lcrypto "-LNative References" -lopus "-LNative References" -lspeex "-LNative 
      References" -lsrtp "-LNative References" -lssl -L../../../.. -lVidyoClient	test.iOS	

Please give me reply proper solution....
![image](https://user-images.githubusercontent.com/24601713/50203270-ee4c7580-0386-11e9-81d8-6f5c21d733ee.png)

**Comment by jcular** [comment]
Hi @RushikPatel,

we don't have VidyoClient library inside our SDK.

Kind regards,
Jure

**Comment by jcular** [comment]
I'm not sure we can help you since we don't maintain VidyoClient library.
You should probably open an issue in the repository of the VidyoClient library maintainers.

Kind regards,
Jure
