### ISSUE TITLE
NSInternalInconsistencyException CroId Name dictionary must not be null!

### ISSUE THREAD

**Issue by hock2k5** [BlinkID/blinkid-xamarin#7]
Hello,

Having an issue running the Xamarin Forms sample and am receiving the follow errors in the application output when the camera is loaded up to start scanning barcodes:

*** Assertion failure in -[PPResourceManager loadDictionaryAndConfusions], /Users/dino/MicroBlink/Workspace/BlinkID/blinkid-ios-demo/blinkid-ios-framework/core-ios/CommonFramework/Services/PPResourceManager.mm:508
Xamarin.iOS: Received unhandled ObjectiveC exception: NSInternalInconsistencyException CroId Name dictionary must not be null!

I was able to get an older version working about 2 weeks ago, but now when pull down the latest with git clone this version is giving the error above.

**Comment by DoDoENT** [comment]
This looks like submodules have not been updated.

Can you try `git submodule update --recursive` and rebuild the project?

**Comment by hock2k5** [comment]
I've been trying to run that command, unfortunately nothing happens when I run it.  I've tried running the command from several different folders.

`Adams-MacBook-Pro-2:blinkid-ios adam$ git submodule update --recursive`
`Adams-MacBook-Pro-2:blinkid-ios adam$`

**Comment by DoDoENT** [comment]
Can you try `git submodule update --init`? You should run this command from folder where you have cloned blinkid-xamarin repository.

**Comment by DoDoENT** [comment]
Also, make sure you have `git lfs` installed and configured with `git lfs install` before cloning anything.

**Comment by hock2k5** [comment]
Ran both, still nothing :-(

I installed git lfs prior per the instructions on the blinkid-ios page.

`Adams-MacBook-Pro-2:blinkid-xamarin-master 3 adam$ git submodule update --init`
```
Adams-MacBook-Pro-2:blinkid-xamarin-master 3 adam$ git lfs
git-lfs/1.4.1 (GitHub; darwin amd64; go 1.7.1)
```

**Comment by DoDoENT** [comment]
If you `cd BindingSource/iOS/blinkid-ios/` and `git rev-parse HEAD`, is the output `108b2d44308db658e2ba0573e8173ee392f6c4b4`?

**Comment by hock2k5** [comment]
No:

`Adams-MacBook-Pro-2:blinkid-ios adam$ git rev-parse HEAD`
`abb9e78acbb095ce547ed70c79a517f790e272e4`

**Comment by DoDoENT** [comment]
OK, this is some strange commit which does not exist anymore. Can you ensure following:

- in blinkid-xamarin clone path you are on latest master branch (commit `f1dcff6d50447043ae6e6792e21cc9a0a55d3bd4`)
- iOS submodule is up-to-date, i.e. `BindingSource/iOS/blinkid-ios` is on tag v2.2.0 (commit `108b2d44308db658e2ba0573e8173ee392f6c4b4`)

If you cannot achieve that using your existing clone, please clone blinkid-xamarin repository anew (together with submodules).

**Comment by hock2k5** [comment]
Cloning it again seemed to fix the issue.

In the .net world I was used to downloading the .zip file rather than doing a `git clone` (at least I personally always do this for packages I want to add into a solution), and I think that may have contributed to some of the issues.

Appreciate the help, the scanning is very quick.

**Comment by DoDoENT** [comment]
I am not sure if downloading the zip also includes submodules and LFS files, so cloning the git seems to be the safest way (you can always make shallow clone if not interested in entire git history).

If your problem is solved, please close the issue.
