### ISSUE TITLE
How to get high resolution scanned document image

### ISSUE THREAD

**Issue by devperson** [BlinkID/blinkid-xamarin#75]
Hi, I am using Xamarin BlinkId to scan documents. Everything works great! My issue is that when I get the scanned document as an ImageSource I see that it is cropped. How can I get the high-resolution scanned image?

**Comment by MBrizic01** [comment]
hi @devperson if would like to obtain the full camera frame, you can do so by adding the following lines of code [here](https://github.com/BlinkID/blinkid-xamarin/blob/897baf109b611b8e170c3970e31adb1d112f802c/Samples/Forms/Core/BlinkIDPage.xaml.cs#L224).
`       blinkidRecognizer.SaveCameraFrames = true;`
and you will obtain the image in the results:
`  if (blinkidRecognizer.Result.ResultState == RecognizerResultState.Valid)
                    {
                        var blinkidResult = blinkidRecognizer.Result;
                        var frontCameraImage = blinkidResult.FrontCameraFrame;`

**Comment by devperson** [comment]
@MBrizic01 Thanks for the response but I don't have such `SaveCameraFrames` property in `IBlinkIdCombinedRecognizer` and the `FrontCameraFrame`  property in `IBlinkIdCombinedRecognizerResult`
I am using BlinkID.Forms version 5.15 (latest version)

**Comment by MBrizic01** [comment]
@devperson Please update to the latest version of our SDK ([5.19.0](https://github.com/BlinkID/blinkid-xamarin/releases/tag/v5.19.0)) to use the full potential of our product. The saveCameraFrame property was added in [5.16.0](https://github.com/BlinkID/blinkid-ios/blob/1dc5ec33f6aa63a1180f2c3b0425120cd5a4f91a/Release%20notes.md#changes-to-blinkidcombined-recognizer-3)

**Comment by devperson** [comment]
@MBrizic01 Thanks after manually installing BlinkID.Forms.Core `version: 5.19.0` I can see those properties. 
JFI: The latest `BlinkID.Forms` version is 5.15 but `BlinkID.Forms.Core` is 5.19.0

**Comment by MBrizic01** [comment]
@devperson great! thanks for your feedback!
